export interface LibraryIcon {
	group: string;
	icon: string;
	name: string;
}

export const EXTRA_ICONS: LibraryIcon[] = [
	{ group: "Servers & tools", icon: "di:apache", name: "Apache" },
	{ group: "Servers & tools", icon: "di:caddy", name: "Caddy" },
	{
		group: "Servers & tools",
		icon: "di:elasticsearch",
		name: "Elasticsearch",
	},
	{ group: "Servers & tools", icon: "kafka.svg", name: "Kafka" },
	{ group: "Servers & tools", icon: "di:mariadb", name: "MariaDB" },
	{ group: "Servers & tools", icon: "di:nginx", name: "Nginx" },
	{ group: "Servers & tools", icon: "di:rabbitmq", name: "RabbitMQ" },
	{ group: "Servers & tools", icon: "sqlite.svg", name: "SQLite" },
	{ group: "Servers & tools", icon: "di:traefik", name: "Traefik" },
	{ group: "Languages", icon: "lang-dotnet.svg", name: ".NET" },
	{ group: "Languages", icon: "lang-bun.svg", name: "Bun" },
	{ group: "Languages", icon: "di:c", name: "C" },
	{ group: "Languages", icon: "di:csharp", name: "C#" },
	{ group: "Languages", icon: "di:cpp", name: "C++" },
	{ group: "Languages", icon: "lang-clojure.svg", name: "Clojure" },
	{ group: "Languages", icon: "di:dart", name: "Dart" },
	{ group: "Languages", icon: "di:deno", name: "Deno" },
	{ group: "Languages", icon: "lang-elixir.svg", name: "Elixir" },
	{ group: "Languages", icon: "lang-erlang.svg", name: "Erlang" },
	{ group: "Languages", icon: "di:go", name: "Go" },
	{ group: "Languages", icon: "lang-haskell.svg", name: "Haskell" },
	{ group: "Languages", icon: "di:java", name: "Java" },
	{ group: "Languages", icon: "di:javascript", name: "JavaScript" },
	{ group: "Languages", icon: "di:kotlin", name: "Kotlin" },
	{ group: "Languages", icon: "di:lua", name: "Lua" },
	{ group: "Languages", icon: "di:nodejs", name: "Node.js" },
	{ group: "Languages", icon: "di:php", name: "PHP" },
	{ group: "Languages", icon: "di:python", name: "Python" },
	{ group: "Languages", icon: "di:ruby", name: "Ruby" },
	{ group: "Languages", icon: "di:rust", name: "Rust" },
	{ group: "Languages", icon: "lang-scala.svg", name: "Scala" },
	{ group: "Languages", icon: "di:swift", name: "Swift" },
	{ group: "Languages", icon: "di:typescript", name: "TypeScript" },
	{ group: "Languages", icon: "lang-zig.svg", name: "Zig" },
	{ group: "Frameworks", icon: "di:angular", name: "Angular" },
	{ group: "Frameworks", icon: "fw-astro.svg", name: "Astro" },
	{ group: "Frameworks", icon: "fw-django.svg", name: "Django" },
	{ group: "Frameworks", icon: "fw-express.svg", name: "Express" },
	{ group: "Frameworks", icon: "fw-fastapi.svg", name: "FastAPI" },
	{ group: "Frameworks", icon: "fw-fastify.svg", name: "Fastify" },
	{ group: "Frameworks", icon: "fw-flask.svg", name: "Flask" },
	{ group: "Frameworks", icon: "fw-gin.svg", name: "Gin" },
	{ group: "Frameworks", icon: "fw-hono.svg", name: "Hono" },
	{ group: "Frameworks", icon: "fw-htmx.svg", name: "htmx" },
	{ group: "Frameworks", icon: "di:laravel", name: "Laravel" },
	{ group: "Frameworks", icon: "fw-nestjs.svg", name: "NestJS" },
	{ group: "Frameworks", icon: "di:nextjs", name: "Next.js" },
	{ group: "Frameworks", icon: "fw-nuxt.svg", name: "Nuxt" },
	{ group: "Frameworks", icon: "fw-phoenix.svg", name: "Phoenix" },
	{ group: "Frameworks", icon: "di:qwik", name: "Qwik" },
	{ group: "Frameworks", icon: "di:ruby-on-rails", name: "Rails" },
	{ group: "Frameworks", icon: "fw-react.svg", name: "React" },
	{ group: "Frameworks", icon: "fw-remix.svg", name: "Remix" },
	{ group: "Frameworks", icon: "fw-solid.svg", name: "SolidJS" },
	{ group: "Frameworks", icon: "fw-spring.svg", name: "Spring" },
	{ group: "Frameworks", icon: "di:svelte", name: "SvelteKit / Svelte" },
	{ group: "Frameworks", icon: "fw-symfony.svg", name: "Symfony" },
	{ group: "Frameworks", icon: "di:vite", name: "Vite" },
	{ group: "Frameworks", icon: "fw-vue.svg", name: "Vue" },
];
