export interface LibraryIcon {
	group: string;
	icon: string;
	name: string;
}

export const EXTRA_ICONS: LibraryIcon[] = [
	{ group: "Servers & tools", icon: "apache.svg", name: "Apache" },
	{ group: "Servers & tools", icon: "caddy.svg", name: "Caddy" },
	{
		group: "Servers & tools",
		icon: "elasticsearch.svg",
		name: "Elasticsearch",
	},
	{ group: "Servers & tools", icon: "kafka.svg", name: "Kafka" },
	{ group: "Servers & tools", icon: "mariadb.svg", name: "MariaDB" },
	{ group: "Servers & tools", icon: "nginx.svg", name: "Nginx" },
	{ group: "Servers & tools", icon: "rabbitmq.svg", name: "RabbitMQ" },
	{ group: "Servers & tools", icon: "sqlite.svg", name: "SQLite" },
	{ group: "Servers & tools", icon: "traefik.svg", name: "Traefik" },
	{ group: "Languages", icon: "lang-dotnet.svg", name: ".NET" },
	{ group: "Languages", icon: "lang-bun.svg", name: "Bun" },
	{ group: "Languages", icon: "lang-c.svg", name: "C" },
	{ group: "Languages", icon: "lang-csharp.svg", name: "C#" },
	{ group: "Languages", icon: "lang-cpp.svg", name: "C++" },
	{ group: "Languages", icon: "lang-clojure.svg", name: "Clojure" },
	{ group: "Languages", icon: "lang-dart.svg", name: "Dart" },
	{ group: "Languages", icon: "lang-deno.svg", name: "Deno" },
	{ group: "Languages", icon: "lang-elixir.svg", name: "Elixir" },
	{ group: "Languages", icon: "lang-erlang.svg", name: "Erlang" },
	{ group: "Languages", icon: "lang-go.svg", name: "Go" },
	{ group: "Languages", icon: "lang-haskell.svg", name: "Haskell" },
	{ group: "Languages", icon: "lang-java.svg", name: "Java" },
	{ group: "Languages", icon: "lang-javascript.svg", name: "JavaScript" },
	{ group: "Languages", icon: "lang-kotlin.svg", name: "Kotlin" },
	{ group: "Languages", icon: "lang-lua.svg", name: "Lua" },
	{ group: "Languages", icon: "lang-nodejs.svg", name: "Node.js" },
	{ group: "Languages", icon: "lang-php.svg", name: "PHP" },
	{ group: "Languages", icon: "lang-python.svg", name: "Python" },
	{ group: "Languages", icon: "lang-ruby.svg", name: "Ruby" },
	{ group: "Languages", icon: "lang-rust.svg", name: "Rust" },
	{ group: "Languages", icon: "lang-scala.svg", name: "Scala" },
	{ group: "Languages", icon: "lang-swift.svg", name: "Swift" },
	{ group: "Languages", icon: "lang-typescript.svg", name: "TypeScript" },
	{ group: "Languages", icon: "lang-zig.svg", name: "Zig" },
	{ group: "Frameworks", icon: "fw-angular.svg", name: "Angular" },
	{ group: "Frameworks", icon: "fw-astro.svg", name: "Astro" },
	{ group: "Frameworks", icon: "fw-django.svg", name: "Django" },
	{ group: "Frameworks", icon: "fw-express.svg", name: "Express" },
	{ group: "Frameworks", icon: "fw-fastapi.svg", name: "FastAPI" },
	{ group: "Frameworks", icon: "fw-fastify.svg", name: "Fastify" },
	{ group: "Frameworks", icon: "fw-flask.svg", name: "Flask" },
	{ group: "Frameworks", icon: "fw-gin.svg", name: "Gin" },
	{ group: "Frameworks", icon: "fw-hono.svg", name: "Hono" },
	{ group: "Frameworks", icon: "fw-htmx.svg", name: "htmx" },
	{ group: "Frameworks", icon: "fw-laravel.svg", name: "Laravel" },
	{ group: "Frameworks", icon: "fw-nestjs.svg", name: "NestJS" },
	{ group: "Frameworks", icon: "fw-nextjs.svg", name: "Next.js" },
	{ group: "Frameworks", icon: "fw-nuxt.svg", name: "Nuxt" },
	{ group: "Frameworks", icon: "fw-phoenix.svg", name: "Phoenix" },
	{ group: "Frameworks", icon: "fw-qwik.svg", name: "Qwik" },
	{ group: "Frameworks", icon: "fw-rails.svg", name: "Rails" },
	{ group: "Frameworks", icon: "fw-react.svg", name: "React" },
	{ group: "Frameworks", icon: "fw-remix.svg", name: "Remix" },
	{ group: "Frameworks", icon: "fw-solid.svg", name: "SolidJS" },
	{ group: "Frameworks", icon: "fw-spring.svg", name: "Spring" },
	{ group: "Frameworks", icon: "fw-svelte.svg", name: "SvelteKit / Svelte" },
	{ group: "Frameworks", icon: "fw-symfony.svg", name: "Symfony" },
	{ group: "Frameworks", icon: "fw-vite.svg", name: "Vite" },
	{ group: "Frameworks", icon: "fw-vue.svg", name: "Vue" },
];
