[run]
bun = true

[test]
preload = [
    "./tests/unit/app/svelte-loader.ts",
    "./tests/unit/support/homedir-preload.ts",
    "./tests/integration/support/setup.ts",
]

# Global test timeout only (whole suite), individal test timeout should be set via cli with --timeout
timeout = 120_000

coverage = true
coveragePathIgnorePatterns = ["tests/**", "packages/cli/generated/**"]
