services:
  traefik:
    extends:
      file: tools/compose/base.compose.yaml
      service: traefik
    volumes:
      - ./traefik-dynamic:/etc/traefik/dynamic
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - homerun
      - internal

  agent:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: agent
    extends:
      file: tools/compose/agent.compose.yaml
      service: agent
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
      - homerun

  postgres:
    extends:
      file: tools/compose/base.compose.yaml
      service: postgres
    networks:
      - internal

networks:
  homerun:
    name: homerun
    external: true
  internal:
    external: false

volumes:
  postgres_data: {}
  traefik_certs: {}
  agent_data: {}
