services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app
    extends:
      file: tools/compose/app.compose.yaml
      service: app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
      - homerun

  agent:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: agent
    extends:
      file: tools/compose/agent.compose.yaml
      service: agent
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
      - homerun

  traefik:
    extends:
      file: tools/compose/base.compose.yaml
      service: traefik
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
      - homerun

  postgres:
    extends:
      file: tools/compose/base.compose.yaml
      service: postgres
    networks:
      - internal

networks:
  homerun:
    name: homerun
    external: true
  internal:
    external: false

volumes:
  postgres_data: {}
  traefik_certs: {}
  agent_data: {}
  app_data: {}
