CREATE TABLE `instance_settings` (
	`auth_check_url` text,
	`auth_cross_subdomain_cookies` integer,
	`auth_origin` text,
	`base_domain` text,
	`created_at` integer NOT NULL,
	`docker_network_name` text,
	`docker_socket_path` text,
	`id` text PRIMARY KEY NOT NULL,
	`oauth_providers` text DEFAULT '[]' NOT NULL,
	`smtp_enabled` integer,
	`smtp_from` text,
	`smtp_host` text,
	`smtp_password_enc` text,
	`smtp_port` integer,
	`smtp_secure` integer,
	`smtp_user` text,
	`traefik_cert_resolver` text,
	`traefik_dynamic_config_dir` text,
	`traefik_entrypoint` text,
	`updated_at` integer NOT NULL
);
