import { describe, expect, test } from "bun:test";
import {
	generateConfiguration,
	type Inventory,
	inventoryCounts,
	localNames,
	scopeToStack,
	terraformName,
} from "../../../src/lib/iac/generate";

const inventory: Inventory = {
	homerun_bucket: [
		{ expirationDays: null, id: "s1/state", name: "state", storeId: "s1" },
	],
	homerun_build_cache_registry: [
		{
			id: "r1",
			name: "GHCR",
			passwordSet: true,
			registryUrl: "ghcr.io",
			username: "me",
		},
	],
	homerun_service: [
		{
			containerPort: 80,
			envVars: { API_KEY: "secret", MODE: "prod" },
			id: "svc-1",
			image: "nginx",
			name: "Web",
			privileged: false,
			publishedPorts: [{ containerPort: 53, hostPort: 5353, protocol: "udp" }],
			replicas: 1,
			secretEnvKeys: ["API_KEY"],
			slug: "web",
			stackId: "stack-1",
			tag: "1.27",
		},
		{
			containerPort: 5432,
			envVars: {},
			id: "svc-2",
			image: "postgres",
			name: "DB",
			slug: "web",
			stackId: "stack-2",
		},
	],
	homerun_service_dependency: [
		{ dependsOnId: "svc-2", id: "dep-1", serviceId: "svc-1" },
	],
	homerun_stack: [
		{ id: "stack-1", name: "Apps", parentId: null, slug: "apps" },
		{ id: "stack-2", name: "Data", parentId: "stack-1", slug: "data" },
		{ id: "stack-3", name: "Other", parentId: null, slug: "other" },
	],
	homerun_status_page: [
		{
			id: "page-1",
			name: "Status",
			scope: "stack",
			slug: "status",
			stackId: "stack-3",
		},
	],
	homerun_volume: [
		{ id: "vol-1", kind: "volume", name: "web-data", source: "web-data" },
		{ id: "vol-2", kind: "bind", name: "elsewhere", source: "/srv" },
	],
	homerun_volume_mount: [
		{
			containerPath: "/data",
			id: "m-1",
			readOnly: false,
			serviceId: "svc-1",
			volumeId: "vol-1",
		},
	],
};

describe("terraformName", () => {
	test("turns free text into a Terraform name", () => {
		expect(terraformName("My App!")).toBe("my_app");
		expect(terraformName("9lives")).toBe("r_9lives");
		expect(terraformName("provider")).toBe("r_provider");
		expect(terraformName("--")).toBe("unnamed");
	});
});

describe("localNames", () => {
	test("dedupes names and names edges after both ends", () => {
		const names = localNames(inventory);
		expect(names.get("homerun_service")?.get("svc-1")).toBe("web");
		expect(names.get("homerun_service")?.get("svc-2")).toBe("web_2");
		expect(names.get("homerun_service_dependency")?.get("dep-1")).toBe(
			"web_on_web_2",
		);
		expect(names.get("homerun_volume_mount")?.get("m-1")).toBe("web_web_data");
		expect(names.get("homerun_bucket")?.get("s1/state")).toBe("state");
	});
});

describe("scopeToStack", () => {
	test("keeps a stack, its substacks and what their services use", () => {
		const scoped = scopeToStack(inventory, "stack-1");
		expect(scoped.homerun_stack?.map((stack) => stack.id)).toEqual([
			"stack-1",
			"stack-2",
		]);
		expect(scoped.homerun_service?.length).toBe(2);
		expect(scoped.homerun_volume?.map((volume) => volume.id)).toEqual([
			"vol-1",
		]);
		expect(scoped.homerun_status_page).toEqual([]);
		expect(scoped.homerun_bucket).toBeUndefined();
		expect(inventoryCounts(scoped).map((entry) => entry.type)).not.toContain(
			"homerun_bucket",
		);
	});
});

describe("generateConfiguration", () => {
	const text = generateConfiguration(inventory, {
		backendAddress: "https://homerun.example.com/api/v1/iac/projects/p1",
		endpoint: "https://homerun.example.com",
		generatedAt: new Date("2026-10-05T12:00:00Z"),
	});

	test("writes the provider, the backend and an import block per object", () => {
		expect(text).toStartWith(
			"# Generated by Homerun on 2026-10-05T12:00:00.000Z.",
		);
		expect(text).toContain('source = "orochibraru/homerun"');
		expect(text).toContain(
			'address        = "https://homerun.example.com/api/v1/iac/projects/p1/state"',
		);
		expect(text).toContain('endpoint = "https://homerun.example.com"');
		expect(text).toContain(
			'import {\n  to = homerun_service.web\n  id = "svc-1"\n}',
		);
		expect(text).toContain(
			'import {\n  to = homerun_bucket.state\n  id = "s1/state"\n}',
		);
	});

	test("references generated objects and leaves defaults out", () => {
		expect(text).toContain("stack_id = homerun_stack.apps.id");
		expect(text).toContain("stack_id       = homerun_stack.data.id");
		expect(text).toContain("parent_id = homerun_stack.apps.id");
		expect(text).toContain("depends_on_id = homerun_service.web_2.id");
		expect(text).not.toContain("replicas");
		expect(text).not.toContain("privileged");
		expect(text).toContain("container_port = 53");
	});

	test("turns secrets into sensitive variables", () => {
		expect(text).toContain('variable "web_api_key" {');
		expect(text).toContain("API_KEY = var.web_api_key");
		expect(text).toContain('MODE    = "prod"');
		expect(text).toContain("password     = var.ghcr_password");
		expect(text).toContain("sensitive   = true");
	});

	test("is stable and works without a backend", () => {
		const options = {
			backendAddress: null,
			endpoint: "http://localhost:3000",
			generatedAt: new Date(0),
		};
		const first = generateConfiguration(inventory, options);
		expect(generateConfiguration(inventory, options)).toBe(first);
		expect(first).not.toContain('backend "http"');
		expect(generateConfiguration({}, options)).toContain('provider "homerun"');
	});
});
