import { dirname, isAbsolute, join, resolve } from "node:path";
import type { UpdateChannel } from "$lib/update-channel";

export const COMPOSE_PROJECT_LABEL = "com.docker.compose.project";
export const COMPOSE_SERVICE_LABEL = "com.docker.compose.service";
export const COMPOSE_WORKING_DIR_LABEL =
	"com.docker.compose.project.working_dir";
export const COMPOSE_CONFIG_FILES_LABEL =
	"com.docker.compose.project.config_files";

export const WORKER_ROLE_LABEL = "homerun.role";
export const WORKER_ROLE = "worker";

export const UPDATER_CONTAINER_NAME = "homerun-updater";
export const UPDATER_IMAGE = "docker";
export const UPDATER_IMAGE_TAG = "cli";

export const CANDIDATE_CONTAINER_NAME = "homerun-update-candidate";
export const AUTH_CHECK_ALIAS = "homerun-auth";
export const READY_PATH = "/api/v1/ready";

export const GENERATED_COMPOSE_FILE = "compose.yaml";
export const GENERATED_SWARM_FILE = "compose.swarm.yaml";
export const IMAGE_COMPOSE_DIR = "/app/compose";

const CONTAINER_SOCKET_PATH = "/var/run/docker.sock";
const GENERATED_MARKER_RE =
	"^# (homerun:generated|Generated by the Homerun installer)";
const ROUTER_RULE_LABEL = "traefik.http.routers.homerun.rule";
const ROUTER_RESOLVER_LABEL = "traefik.http.routers.homerun.tls.certresolver";
const HOST_RULE_RE = /Host\(`([^`]+)`\)/;
const MOUNTINFO_CONTAINER_RE = /\/containers\/([0-9a-f]{64})\//;
const TAG_SAFE_RE = /^[\w.-]+$/;

export interface ComposeTarget {
	configFiles: string[];
	image: string;
	project: string;
	service: string;
	workingDir: string;
}

export interface ImageRef {
	repository: string;
	tag: string | null;
}

/**
 * Reads a running container's own Docker Compose labels to recover the
 * project/service/working-dir/config-files it was launched from, so the
 * updater can run `docker compose ... pull && up -d` against that same
 * project. Returns null if any required label is missing or the working
 * directory isn't an absolute path (i.e. the container wasn't launched via
 * Compose, or the label set is unusable).
 */
export function composeTargetFrom(
	labels: Record<string, string> | null | undefined,
	image: string,
): ComposeTarget | null {
	const project = labels?.[COMPOSE_PROJECT_LABEL]?.trim();
	const service = labels?.[COMPOSE_SERVICE_LABEL]?.trim();
	const workingDir = labels?.[COMPOSE_WORKING_DIR_LABEL]?.trim();
	if (!(project && service && workingDir && isAbsolute(workingDir))) {
		return null;
	}
	const configFiles = (labels?.[COMPOSE_CONFIG_FILES_LABEL] ?? "")
		.split(",")
		.map((file) => file.trim())
		.filter(Boolean)
		.map((file) => (isAbsolute(file) ? file : resolve(workingDir, file)));
	return { configFiles, image, project, service, workingDir };
}

/** Extracts this container's own 64-char id from `/proc/self/mountinfo`'s content, or null if none of its mount paths look like a container overlay path. */
export function containerIdFromMountinfo(mountinfo: string): string | null {
	return MOUNTINFO_CONTAINER_RE.exec(mountinfo)?.[1] ?? null;
}

/** Splits an image reference into repository and tag, defaulting to `"latest"` when untagged and digest-less, or `null` when pinned by digest (`@sha256:...`). */
export function splitImageRef(ref: string): ImageRef {
	const withoutDigest = ref.split("@")[0] ?? ref;
	const lastColon = withoutDigest.lastIndexOf(":");
	const lastSlash = withoutDigest.lastIndexOf("/");
	if (lastColon === -1 || lastColon < lastSlash) {
		return {
			repository: withoutDigest,
			tag: ref.includes("@") ? null : "latest",
		};
	}
	return {
		repository: withoutDigest.slice(0, lastColon),
		tag: withoutDigest.slice(lastColon + 1),
	};
}

/**
 * The tag to rewrite the compose file/`.env` to for `latestVersion` on
 * `channel`, or null to keep the current one. Canary and nightly always run
 * the moving tag named after the channel. Stable keeps `latest` or a digest pin as they are (a pull
 * already gets the newest image) and otherwise pins the release, preserving
 * the current tag's `v` prefix style, which is also how an instance switched
 * back from canary or nightly returns to a stable tag.
 */
export function pinnedTagFor(
	currentTag: string | null,
	latestVersion: string,
	channel: UpdateChannel,
): string | null {
	if (channel !== "stable") {
		return currentTag === channel ? null : channel;
	}
	if (currentTag === null || currentTag === "latest") {
		return null;
	}
	const bare = latestVersion.replace(/^v/, "");
	const next = /^\d/.test(currentTag) ? bare : `v${bare}`;
	return next === currentTag ? null : next;
}

function shellQuote(value: string): string {
	return `'${value.replaceAll("'", `'\\''`)}'`;
}

function escapeRegex(value: string): string {
	return value.replace(/[.*+?^${}()|[\]\\/#]/g, "\\$&");
}

/**
 * The `.env` values a generated compose file reads, recovered from the running
 * app for an install whose compose file predates them (it baked the host,
 * socket and cert resolver in instead). The updater only writes a key `.env`
 * doesn't already have, so these never override the admin's own values.
 */
export function composeEnvDefaults(
	labels: Record<string, string> | null | undefined,
	origin: string | undefined,
	hostSocketPath: string,
): Record<string, string> {
	const defaults: Record<string, string> = {
		HOMERUN_DOCKER_SOCKET: hostSocketPath,
	};
	const host = HOST_RULE_RE.exec(labels?.[ROUTER_RULE_LABEL] ?? "")?.[1];
	if (host) {
		defaults.HOMERUN_HOST = host;
	}
	const resolver = labels?.[ROUTER_RESOLVER_LABEL];
	if (resolver !== undefined) {
		defaults.DASHBOARD_CERT_RESOLVER = resolver;
	}
	if (origin) {
		defaults.ORIGIN = origin;
	}
	return defaults;
}

/** Shell lines extracting one file from the new app image's `/app/compose` into the working dir, rewriting it in place so its owner and mode survive. */
function extractFromImage(image: string, file: string): string[] {
	return [
		`docker run --rm --entrypoint cat ${shellQuote(image)} ${shellQuote(`${IMAGE_COMPOSE_DIR}/${file}`)} > ${shellQuote(`${file}.next`)}`,
		`cat ${shellQuote(`${file}.next`)} > ${shellQuote(file)}`,
		`rm -f ${shellQuote(`${file}.next`)}`,
	];
}

/**
 * Shell lines for an install running Homerun's generated compose file: fills
 * in the `.env` keys it reads and doesn't have yet from `envDefaults`, points
 * `HOMERUN_IMAGE`/`HOMERUN_VERSION` at the target image, then overwrites
 * `compose.yaml` (and `compose.swarm.yaml`, when the install is a swarm one)
 * with the files that image ships, and leaves the matching `-f` flags in `$@`.
 */
function generatedComposeLines(
	image: string,
	repository: string,
	tag: string,
	envDefaults: Record<string, string>,
): string[] {
	const missing = { HOMERUN_IMAGE: repository, ...envDefaults };
	return [
		"echo '==> Refreshing the generated compose file'",
		"touch .env",
		`if [ -n "$(tail -c 1 .env)" ]; then echo >> .env; fi`,
		...Object.entries(missing).map(
			([key, value]) =>
				`grep -q ${shellQuote(`^${key}=`)} .env || printf '%s\\n' ${shellQuote(`${key}=${value}`)} >> .env`,
		),
		`{ grep -v '^HOMERUN_VERSION=' .env || true; printf '%s\\n' ${shellQuote(`HOMERUN_VERSION=${tag}`)}; } > .env.next`,
		"cat .env.next > .env",
		"rm -f .env.next",
		`docker pull ${shellQuote(image)}`,
		`if [ -f ${GENERATED_SWARM_FILE} ] || grep -q 'providers.swarm' ${GENERATED_COMPOSE_FILE}; then`,
		...extractFromImage(image, GENERATED_SWARM_FILE),
		`set -- -f ${GENERATED_COMPOSE_FILE} -f ${GENERATED_SWARM_FILE}`,
		"else",
		`set -- -f ${GENERATED_COMPOSE_FILE}`,
		"fi",
		...extractFromImage(image, GENERATED_COMPOSE_FILE),
	];
}

/**
 * Shell lines for a hand-written compose file, which is never replaced: when
 * the current tag is a pinnable version tag, rewrites it in place across the
 * compose files and `.env` (via `sed`) so a version-pinned deployment tracks
 * the new release, and leaves the compose files' `-f` flags in `$@`.
 */
function handWrittenComposeLines(
	target: ComposeTarget,
	repository: string,
	tag: string | null,
	nextTag: string | null,
): string[] {
	const lines: string[] = [];
	if (tag && nextTag && TAG_SAFE_RE.test(tag) && TAG_SAFE_RE.test(nextTag)) {
		const repoName = repository.split("/").pop() ?? repository;
		const imageExpr = `s#(${escapeRegex(repoName)}:)${escapeRegex(tag)}([^A-Za-z0-9_.-]|$)#\\1${nextTag}\\2#g`;
		const envExpr = `s#^(HOMERUN_VERSION=["']?)${escapeRegex(tag)}(["']?[[:space:]]*)$#\\1${nextTag}\\2#`;
		if (target.configFiles.length > 0) {
			lines.push(
				`sed -E -i ${shellQuote(imageExpr)} ${target.configFiles.map(shellQuote).join(" ")}`,
			);
		}
		lines.push(
			`if [ -f .env ]; then sed -E -i ${shellQuote(envExpr)} .env; fi`,
		);
	}
	lines.push(
		[
			"set --",
			...target.configFiles.map((file) => `-f ${shellQuote(file)}`),
		].join(" "),
	);
	return lines;
}

/**
 * Builds the shell script the updater container runs, moving the install to
 * `release`'s version on its channel (see `pinnedTagFor`). An install running
 * Homerun's generated compose file (its `# homerun:generated` marker, or the
 * older installer header) gets that file overwritten with the one the new
 * release's image ships, since an old file can be incompatible with a new
 * image; a hand-written one only gets its pinned tag bumped. Either way it
 * then pulls and recreates this service plus `companions` (the
 * homerun-worker service running from the same image) with `--no-deps`, so
 * Traefik, Postgres and anything outside the project (the Newt tunnel) are
 * never touched.
 */
export function updaterScript(
	target: ComposeTarget,
	release: { channel: UpdateChannel; version: string },
	{
		companions = [],
		envDefaults = {},
		network = "homerun",
	}: {
		companions?: string[];
		envDefaults?: Record<string, string>;
		network?: string;
	} = {},
): string {
	const { channel, version: latestVersion } = release;
	const { repository, tag } = splitImageRef(target.image);
	const nextTag = pinnedTagFor(tag, latestVersion, channel);
	const imageTag = nextTag ?? tag ?? "latest";
	const compose = `docker compose -p ${shellQuote(target.project)} "$@"`;
	const services = [...new Set([target.service, ...companions])]
		.map(shellQuote)
		.join(" ");
	const backedUp = [
		...target.configFiles,
		join(target.workingDir, ".env"),
		join(target.workingDir, GENERATED_SWARM_FILE),
	]
		.map(shellQuote)
		.join(" ");
	const candidate = shellQuote(CANDIDATE_CONTAINER_NAME);
	const net = shellQuote(network);
	return [
		"set -eu",
		`echo ${shellQuote(`==> Updating Homerun to v${latestVersion}`)}`,
		`cd ${shellQuote(target.workingDir)}`,
		...safetyNetLines(backedUp),
		`if [ -f ${GENERATED_COMPOSE_FILE} ] && grep -qE ${shellQuote(GENERATED_MARKER_RE)} ${GENERATED_COMPOSE_FILE}; then`,
		...generatedComposeLines(
			`${repository}:${imageTag}`,
			repository,
			imageTag,
			envDefaults,
		),
		"else",
		...handWrittenComposeLines(target, repository, tag, nextTag),
		"fi",
		"echo '==> Pulling the new images'",
		`${compose} pull ${services}`,
		"echo '==> Checking the new version before switching to it'",
		`docker rm -f ${candidate} >/dev/null 2>&1 || true`,
		`if ! ${compose} run -d --no-deps --name ${candidate} -e HOMERUN_CANDIDATE=1 -l traefik.enable=false ${shellQuote(target.service)} >/dev/null || ! wait_ready ${candidate}; then`,
		`	echo ${shellQuote(`==> v${latestVersion} failed its check: staying on the current version`)}`,
		`	docker logs --tail 40 ${candidate} 2>&1 || true`,
		`	docker rm -f ${candidate} >/dev/null 2>&1 || true`,
		"	restore",
		"	exit 1",
		"fi",
		"echo '==> Keeping the login wall answering while the containers switch'",
		`if docker network disconnect ${net} ${candidate} >/dev/null 2>&1; then docker network connect --alias ${AUTH_CHECK_ALIAS} ${net} ${candidate} >/dev/null 2>&1 || true; fi`,
		"echo '==> Recreating the Homerun containers'",
		`${compose} up -d --no-deps ${services}`,
		"echo '==> Waiting for the new version to answer'",
		`app=$(${compose} ps -q ${shellQuote(target.service)} | head -n 1)`,
		'if [ -z "$app" ] || ! wait_ready "$app"; then',
		`	echo ${shellQuote(`==> v${latestVersion} didn't come up: rolling back`)}`,
		"	restore",
		`	${compose} up -d --no-deps ${services}`,
		`	app=$(${compose} ps -q ${shellQuote(target.service)} | head -n 1)`,
		'	if [ -n "$app" ]; then wait_ready "$app" || true; fi',
		`	docker rm -f ${candidate} >/dev/null 2>&1 || true`,
		"	exit 1",
		"fi",
		`docker rm -f ${candidate} >/dev/null 2>&1 || true`,
		"forget",
		"echo '==> Done'",
	].join("\n");
}

/**
 * Shell helpers the updater's safety net uses: a copy of every file it may
 * rewrite (`restore` puts them back in place, keeping owner and mode;
 * `forget` drops the copies once the update held), and `wait_ready`, which
 * polls a container's `/api/v1/ready` through the image's own healthcheck
 * binary until it answers or the container stops.
 * `HOMERUN_CHECK_TRIES`/`HOMERUN_CHECK_INTERVAL` exist for the tests.
 */
function safetyNetLines(backedUp: string): string[] {
	return [
		`for f in ${backedUp}; do if [ -f "$f" ]; then cp -p "$f" "$f.homerun-rollback"; fi; done`,
		`restore() { for f in ${backedUp}; do if [ -f "$f.homerun-rollback" ]; then cat "$f.homerun-rollback" > "$f"; rm -f "$f.homerun-rollback"; fi; done; }`,
		`forget() { for f in ${backedUp}; do rm -f "$f.homerun-rollback"; done; }`,
		`ready() { docker exec \${2:+-e PORT=$2} -e HEALTHCHECK_PATH=${READY_PATH} "$1" /app/build/healthcheck >/dev/null 2>&1; }`,
		'wait_ready() { i=0; while [ "$i" -lt "${HOMERUN_CHECK_TRIES:-60}" ]; do if ready "$1" "${2:-}"; then return 0; fi; if [ "$(docker inspect -f \'{{.State.Running}}\' "$1" 2>/dev/null)" != true ]; then return 1; fi; i=$((i + 1)); sleep "${HOMERUN_CHECK_INTERVAL:-2}"; done; return 1; }',
	];
}

/** Bind mounts the updater container needs: the host Docker socket, plus every compose working/config directory so the rewritten files and `docker compose` invocation land on the host's real paths. */
export function updaterBinds(
	target: ComposeTarget,
	hostSocketPath: string,
): string[] {
	const dirs = new Set([
		target.workingDir,
		...target.configFiles.map((file) => dirname(file)),
	]);
	return [
		`${hostSocketPath}:${CONTAINER_SOCKET_PATH}`,
		...[...dirs].map((dir) => `${dir}:${dir}`),
	];
}
