services:
  agent:
    restart: unless-stopped
    stop_grace_period: 125s
    ports:
      - "7420:7420"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - agent_data:/root/.homerun-worker
    environment:
      DOCKER_SOCKET_PATH: /var/run/docker.sock
      WORKER_PORT: 7420
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 5s
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://0.0.0.0:7420/v1/health",
        ]
      timeout: 30s
