import { randomBytes } from "node:crypto";
import type { StepRunner } from "../exec";

/** `--mode=full`'s AUTH_SECRET provisioning, grouped as a class for consistency with the rest of installer/steps/. */
class AuthSecretInstallerService {
	/**
	 * Generates AUTH_SECRET once and persists it to `.env` next to the compose
	 * file, the same "generate once, remember it, tighten the permissions
	 * afterward" shape as the Homerun Agent's own token
	 * (packages/agent/token.ts's `resolveToken`) : docker compose reads a `.env`
	 * file next to its compose.yaml automatically, so nothing else has to
	 * change for the app service's existing `AUTH_SECRET: ${AUTH_SECRET:?...}`
	 * to pick it up. A value already present in `.env`, generated by a prior
	 * run or set by the admin, always wins ; this never overwrites one.
	 */
	async ensureAuthSecret(
		run: StepRunner,
		username: string,
		composeDir: string,
	): Promise<void> {
		const envPath = `${composeDir}/.env`;
		if (await this.#hasAuthSecret(envPath)) {
			return;
		}
		const secret = randomBytes(32).toString("hex");
		await run.appendLine(envPath, `AUTH_SECRET=${secret}`);
		// Bun.write has no mode option honored reliably here either (see
		// packages/agent/token.ts's own note on this), so tighten permissions
		// with an explicit chmod the same way, then hand ownership to the
		// rootless user this compose stack actually runs as.
		await run.run(["chmod", "600", envPath]);
		await run.run(["chown", `${username}:${username}`, envPath]);
	}

	async #hasAuthSecret(envPath: string): Promise<boolean> {
		const file = Bun.file(envPath);
		if (!(await file.exists())) {
			return false;
		}
		const content = await file.text();
		return content
			.split("\n")
			.some((line) => line.trim().startsWith("AUTH_SECRET="));
	}
}

export const AuthSecretInstaller = new AuthSecretInstallerService();
