import type { StepRunner } from "../exec";
import { ReleaseAssets } from "./release";

class FullStackInstallerService {
	/** --mode=full: brings up the actual Homerun app (Traefik + Postgres + the app itself, all as pulled images) under the same rootless user/daemon as everything else this installer sets up. Returns the compose file path it wrote, for the "how to check on it" hint printed at the end. */
	async bringUpFullStack(
		run: StepRunner,
		username: string,
		version: string,
		dockerSocket: string,
	): Promise<string> {
		const composeDir = `/home/${username}/homerun`;
		const composePath = `${composeDir}/compose.yaml`;
		const env = {
			DOCKER_HOST: `unix://${dockerSocket}`,
			HOME: `/home/${username}`,
		};

		await run.run(["mkdir", "-p", composeDir], { as: username });
		await run.writeFile(
			composePath,
			this.#fullStackCompose(ReleaseAssets.imageRef(version), dockerSocket),
		);
		await run.run(["chown", "-R", `${username}:${username}`, composeDir]);

		await run.run(["docker", "compose", "-f", composePath, "pull"], {
			as: username,
			cwd: composeDir,
			env,
		});
		await run.run(["docker", "compose", "-f", composePath, "up", "-d"], {
			as: username,
			cwd: composeDir,
			env,
		});

		return composePath;
	}

	/**
	 * A standalone production compose file, generated here rather than reused
	 * from the repo's own root `compose.yaml`, that file is dev-only (no `app`
	 * service ; the app runs via `bun run dev`/`bun run start` directly on the
	 * host, see its own top comment) and this installer no longer clones the
	 * repo at all. This mirrors its Traefik/Postgres config and adds the `app`
	 * service pointed at the published Docker image : everything here is
	 * pulled, nothing is built.
	 */
	#fullStackCompose(image: string, dockerSocket: string): string {
		return `# Generated by the Homerun installer (--mode=full). Every image below is
# pulled, not built, re-run \`docker compose -f compose.yaml pull && ...up -d\`
# here to update. Set AUTH_SECRET (and ideally the others) in a .env file
# next to this compose.yaml before first \`up\`.
services:
  app:
    image: ${image}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://\${POSTGRES_USER:-homerun}:\${POSTGRES_PASSWORD:-homerun}@postgres:5432/\${POSTGRES_DB:-homerun}
      DOCKER_NETWORK_NAME: homerun
      DOCKER_SOCKET_PATH: ${dockerSocket}
      ORIGIN: \${HOMERUN_ORIGIN:-http://localhost:3000}
      BASE_DOMAIN: \${HOMERUN_BASE_DOMAIN:-localhost}
      AUTH_SECRET: \${AUTH_SECRET:?set AUTH_SECRET in .env before starting, e.g. openssl rand -hex 32}
    ports:
      - "3000:3000"
    volumes:
      - ${dockerSocket}:${dockerSocket}
      - homerun-data:/app/data
    networks:
      - homerun
      - default

  traefik:
    image: traefik:v3
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=homerun
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=\${ACME_EMAIL:-admin@example.com}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${dockerSocket}:${dockerSocket}:ro
      - traefik-certs:/letsencrypt
    networks:
      - homerun

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: \${POSTGRES_DB:-homerun}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-homerun}
      POSTGRES_USER: \${POSTGRES_USER:-homerun}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      interval: 5s
      retries: 5
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-homerun}"]
      timeout: 5s

networks:
  homerun:
    name: homerun
    external: true

volumes:
  postgres-data: {}
  traefik-certs: {}
  homerun-data: {}
`;
	}
}

export const FullStackInstaller = new FullStackInstallerService();
