import type { BuiltinTemplate } from "$lib/server/db/builtin-templates";

export const BUILTIN_TEMPLATES_APPS: BuiltinTemplate[] = [
	{
		category: "analytics",
		containerPort: 3000,
		description:
			"Privacy-focused web analytics. Needs a linked Postgres database.",
		envVars: {
			APP_SECRET: "change-me-to-a-random-32-char-string",
			DATABASE_URL:
				"postgresql://{{db.POSTGRES_USER}}:{{db.POSTGRES_PASSWORD}}@{{db}}:5432/{{db.POSTGRES_DB}}",
		},
		icon: "umami.svg",
		id: "builtin-umami",
		image: "ghcr.io/umami-software/umami",
		sourceUrl: "https://github.com/umami-software/umami",
		name: "Umami",
		tag: "postgresql-latest",
		tags: ["analytics", "privacy", "statistics", "web"],
		websiteUrl: "https://umami.is",
	},
	{
		category: "analytics",
		containerPort: 3000,
		description:
			"BI/dashboards over your own data sources. Runs standalone with an embedded database.",
		envVars: {},
		icon: "metabase.svg",
		id: "builtin-metabase",
		image: "metabase/metabase",
		sourceUrl: "https://github.com/metabase/metabase",
		name: "Metabase",
		tag: "latest",
		tags: ["analytics", "bi", "dashboards", "sql"],
		websiteUrl: "https://www.metabase.com",
	},
	{
		category: "monitoring",
		containerPort: 3000,
		description: "Dashboards and visualization for metrics.",
		envVars: {},
		icon: "grafana.svg",
		id: "builtin-grafana",
		image: "grafana/grafana",
		sourceUrl: "https://github.com/grafana/grafana",
		name: "Grafana",
		tag: "latest",
		tags: ["dashboards", "metrics", "observability", "charts"],
		websiteUrl: "https://grafana.com",
	},
	{
		category: "monitoring",
		containerPort: 8000,
		description: "Cron job and scheduled task monitoring.",
		envVars: {},
		icon: "healthchecks.svg",
		id: "builtin-healthchecks",
		image: "healthchecks/healthchecks",
		sourceUrl: "https://github.com/healthchecks/healthchecks",
		name: "Healthchecks",
		tag: "latest",
		tags: ["cron", "monitoring", "alerts", "heartbeat"],
		websiteUrl: "https://healthchecks.io",
	},
	{
		category: "monitoring",
		containerPort: 8080,
		description: "Lightweight uptime/status monitoring dashboard.",
		envVars: {},
		icon: "gatus.svg",
		id: "builtin-gatus",
		image: "ghcr.io/twin/gatus",
		sourceUrl: "https://github.com/TwiN/gatus",
		name: "Gatus",
		tag: "latest",
		tags: ["uptime", "status", "health", "monitoring"],
		websiteUrl: null,
	},
	{
		category: "monitoring",
		containerPort: 5000,
		description: "Watches web pages for changes and notifies you.",
		envVars: {},
		icon: "changedetection.svg",
		id: "builtin-changedetection",
		image: "dgtlmoon/changedetection.io",
		sourceUrl: "https://github.com/dgtlmoon/changedetection.io",
		name: "changedetection.io",
		tag: "latest",
		tags: ["scraping", "alerts", "websites", "monitoring"],
		websiteUrl: "https://changedetection.io",
	},
	{
		category: "other",
		containerPort: 9090,
		description: "Minimal, fast bookmark manager.",
		envVars: {},
		icon: "linkding.svg",
		id: "builtin-linkding",
		image: "sissbruecker/linkding",
		sourceUrl: "https://github.com/sissbruecker/linkding",
		name: "Linkding",
		tag: "latest",
		tags: ["bookmarks", "links", "read-later"],
		websiteUrl: null,
	},
	{
		category: "other",
		containerPort: 8080,
		description:
			"Minimalist RSS reader. Needs a linked Postgres database, seeds an initial admin account on first boot (change the placeholder password after logging in).",
		envVars: {
			ADMIN_PASSWORD: "changeme123",
			ADMIN_USERNAME: "admin",
			CREATE_ADMIN: "1",
			DATABASE_URL:
				"postgres://{{db.POSTGRES_USER}}:{{db.POSTGRES_PASSWORD}}@{{db}}:5432/{{db.POSTGRES_DB}}?sslmode=disable",
			RUN_MIGRATIONS: "1",
		},
		icon: "miniflux.svg",
		id: "builtin-miniflux",
		image: "miniflux/miniflux",
		sourceUrl: "https://github.com/miniflux/v2",
		name: "Miniflux",
		tag: "latest",
		tags: ["rss", "feeds", "reader", "news"],
		websiteUrl: "https://miniflux.app",
	},
	{
		category: "other",
		containerPort: 80,
		description: "RSS feed aggregator with an embedded SQLite database.",
		envVars: {},
		icon: "freshrss.svg",
		id: "builtin-freshrss",
		image: "freshrss/freshrss",
		sourceUrl: "https://github.com/FreshRSS/FreshRSS",
		name: "FreshRSS",
		tag: "latest",
		tags: ["rss", "feeds", "reader", "news"],
		websiteUrl: "https://freshrss.org",
	},
	{
		category: "other",
		containerPort: 80,
		description:
			"World's most-used blogging and CMS engine. Needs a linked MySQL database.",
		envVars: {
			WORDPRESS_DB_HOST: "{{db}}",
			WORDPRESS_DB_NAME: "{{db.MYSQL_DATABASE}}",
			WORDPRESS_DB_PASSWORD: "{{db.MYSQL_ROOT_PASSWORD}}",
			WORDPRESS_DB_USER: "root",
		},
		icon: "wordpress.svg",
		id: "builtin-wordpress",
		image: "wordpress",
		sourceUrl: "https://github.com/WordPress/WordPress",
		name: "WordPress",
		tag: "latest",
		tags: ["cms", "blog", "website", "php"],
		websiteUrl: "https://wordpress.org",
	},
	{
		category: "other",
		containerPort: 2368,
		description:
			"Blogging platform, runs standalone with an embedded SQLite database.",
		envVars: {},
		icon: "ghost.png",
		id: "builtin-ghost",
		image: "ghost",
		sourceUrl: "https://github.com/TryGhost/Ghost",
		name: "Ghost",
		tag: "latest",
		tags: ["cms", "blog", "newsletter", "publishing"],
		websiteUrl: "https://ghost.org",
	},
	{
		category: "other",
		containerPort: 8384,
		description: "Continuous, peer-to-peer file synchronization.",
		envVars: {},
		icon: "syncthing.svg",
		id: "builtin-syncthing",
		image: "syncthing/syncthing",
		sourceUrl: "https://github.com/syncthing/syncthing",
		name: "Syncthing",
		tag: "latest",
		tags: ["sync", "files", "backup", "p2p"],
		websiteUrl: "https://syncthing.net",
	},
	{
		category: "other",
		containerPort: 80,
		description: "Web-based file browser for a mounted directory.",
		envVars: {},
		icon: "filebrowser.svg",
		id: "builtin-filebrowser",
		image: "filebrowser/filebrowser",
		sourceUrl: "https://github.com/filebrowser/filebrowser",
		name: "File Browser",
		tag: "latest",
		tags: ["files", "storage", "web-ui", "sharing"],
		websiteUrl: "https://filebrowser.org",
	},
	{
		category: "development",
		containerPort: 3000,
		description:
			"Self-hosted Git service, GitHub-alike. Shows a setup wizard on first visit (choose SQLite there for a zero-config start).",
		envVars: {},
		icon: "gitea.svg",
		id: "builtin-gitea",
		image: "gitea/gitea",
		sourceUrl: "https://github.com/go-gitea/gitea",
		name: "Gitea",
		tag: "latest",
		tags: ["git", "forge", "ci", "code"],
		websiteUrl: "https://about.gitea.com",
	},
	{
		category: "development",
		containerPort: 80,
		description: "Collection of handy developer utilities in one static site.",
		envVars: {},
		icon: "it-tools.svg",
		id: "builtin-it-tools",
		image: "ghcr.io/corentinth/it-tools",
		sourceUrl: "https://github.com/CorentinTh/it-tools",
		name: "IT Tools",
		tag: "latest",
		tags: ["tools", "utilities", "developer", "converters"],
		websiteUrl: "https://it-tools.tech",
	},
	{
		category: "other",
		containerPort: 8080,
		description: "Self-hosted PDF manipulation toolkit.",
		envVars: {},
		icon: "stirling-pdf.svg",
		id: "builtin-stirling-pdf",
		image: "stirlingtools/stirling-pdf",
		sourceUrl: "https://github.com/Stirling-Tools/Stirling-PDF",
		name: "Stirling PDF",
		tag: "latest",
		tags: ["pdf", "documents", "tools", "convert"],
		websiteUrl: "https://stirlingpdf.com",
	},
	{
		category: "other",
		containerPort: 9000,
		description: "Self-hosted web IRC client.",
		envVars: {},
		icon: "thelounge.svg",
		id: "builtin-thelounge",
		image: "thelounge/thelounge",
		sourceUrl: "https://github.com/thelounge/thelounge",
		name: "The Lounge",
		tag: "latest",
		tags: ["irc", "chat", "messaging"],
		websiteUrl: "https://thelounge.chat",
	},
	{
		category: "other",
		containerPort: 3000,
		description:
			"Self-hosted drive : a Nextcloud, ownCloud and Google Drive alternative. Set ORIGIN to the URL you'll reach it at, the rest works out of the box on SQLite.",
		envVars: {
			APP_NAME: "Penombre",
			DATABASE_URL: "file:/data/db/penombre.sqlite",
			ORIGIN: "https://drive.example.com",
			STORAGE_PATH: "/data/storage",
		},
		icon: "",
		id: "builtin-penombre",
		image: "orochibraru/penombre",
		sourceUrl: "https://github.com/orochibraru/penombre",
		name: "Penombre",
		tag: "latest",
		tags: ["drive", "files", "storage", "sync", "nextcloud-alternative"],
		websiteUrl: "https://orochibraru.com/penombre",
	},
	{
		category: "other",
		containerPort: 80,
		description:
			"Files, calendars and contacts, with an app store on top. Runs on SQLite as deployed here; link a Postgres for anything beyond a personal instance.",
		envVars: {},
		icon: "nextcloud.svg",
		id: "builtin-nextcloud",
		image: "nextcloud",
		sourceUrl: "https://github.com/nextcloud/server",
		name: "Nextcloud",
		tag: "stable",
		tags: ["files", "drive", "storage", "calendar", "contacts"],
		websiteUrl: "https://nextcloud.com",
	},
	{
		category: "automation",
		containerPort: 8123,
		description:
			"Home automation hub. Device discovery on the local network needs host networking, which this deploy doesn't use : integrations reached over IP still work.",
		envVars: { TZ: "UTC" },
		icon: "home-assistant.svg",
		id: "builtin-home-assistant",
		image: "ghcr.io/home-assistant/home-assistant",
		sourceUrl: "https://github.com/home-assistant/core",
		name: "Home Assistant",
		tag: "stable",
		tags: ["home", "automation", "iot", "smart-home"],
		websiteUrl: "https://www.home-assistant.io",
	},
	{
		category: "productivity",
		containerPort: 9000,
		description:
			"Recipe manager and meal planner. Set BASE_URL to the URL you'll reach it at, or shared links point at the wrong host.",
		envVars: {
			ALLOW_SIGNUP: "false",
			BASE_URL: "https://mealie.example.com",
			TZ: "UTC",
		},
		icon: "mealie.svg",
		id: "builtin-mealie",
		image: "ghcr.io/mealie-recipes/mealie",
		sourceUrl: "https://github.com/mealie-recipes/mealie",
		name: "Mealie",
		tag: "latest",
		tags: ["recipes", "cooking", "meal-planning", "food"],
		websiteUrl: "https://mealie.io",
	},
	{
		category: "productivity",
		containerPort: 5230,
		description:
			"Lightweight note-taking : plain markdown, no folders, an API for everything.",
		envVars: {},
		icon: "",
		id: "builtin-memos",
		image: "neosmemo/memos",
		sourceUrl: "https://github.com/usememos/memos",
		name: "Memos",
		tag: "stable",
		tags: ["notes", "markdown", "microblog", "writing"],
		websiteUrl: "https://usememos.com",
	},
	{
		category: "productivity",
		containerPort: 8000,
		description:
			"Scans, indexes and OCRs your documents. Needs the linked Redis, and a secret key you should change before deploying.",
		envVars: {
			PAPERLESS_REDIS: "redis://{{redis}}:6379",
			PAPERLESS_SECRET_KEY: "change-me-to-a-random-string",
			PAPERLESS_TIME_ZONE: "UTC",
			PAPERLESS_URL: "https://paperless.example.com",
		},
		icon: "paperless-ngx.svg",
		id: "builtin-paperless-ngx",
		image: "ghcr.io/paperless-ngx/paperless-ngx",
		sourceUrl: "https://github.com/paperless-ngx/paperless-ngx",
		name: "Paperless-ngx",
		tag: "latest",
		tags: ["documents", "ocr", "scanning", "archive", "pdf"],
		websiteUrl: "https://docs.paperless-ngx.com",
	},
	{
		category: "monitoring",
		containerPort: 8090,
		description:
			"Lightweight server monitoring hub. Each machine you want graphed runs the separate Beszel agent and reports in here.",
		envVars: {},
		icon: "beszel.svg",
		id: "builtin-beszel",
		image: "henrygd/beszel",
		sourceUrl: "https://github.com/henrygd/beszel",
		name: "Beszel",
		tag: "latest",
		tags: ["monitoring", "metrics", "servers", "dashboards"],
		websiteUrl: "https://beszel.dev",
	},
	{
		category: "media",
		containerPort: 5000,
		description:
			"Reading server for comics, manga and books, with per-user progress tracking.",
		envVars: { TZ: "UTC" },
		icon: "kavita.svg",
		id: "builtin-kavita",
		image: "jvmilazz0/kavita",
		sourceUrl: "https://github.com/Kareadita/Kavita",
		name: "Kavita",
		tag: "latest",
		tags: ["books", "comics", "manga", "ebooks", "reading"],
		websiteUrl: "https://www.kavitareader.com",
	},
	{
		category: "development",
		containerPort: 8443,
		description:
			"VS Code in the browser. Set a password before deploying : the default image has none.",
		envVars: {
			PASSWORD: "change-me",
			PGID: "1000",
			PUID: "1000",
			TZ: "UTC",
		},
		icon: "code-server.svg",
		id: "builtin-code-server",
		image: "lscr.io/linuxserver/code-server",
		sourceUrl: "https://github.com/coder/code-server",
		name: "code-server",
		tag: "latest",
		tags: ["ide", "vscode", "development", "editor"],
		websiteUrl: "https://coder.com/docs/code-server",
	},
	{
		category: "development",
		containerPort: 5000,
		description:
			"The Docker registry itself : somewhere to push your own images, including as a build cache for git-based services.",
		envVars: {},
		icon: "docker.svg",
		id: "builtin-registry",
		image: "registry",
		sourceUrl: "https://github.com/distribution/distribution",
		name: "Docker Registry",
		tag: "2",
		tags: ["registry", "docker", "images", "cache"],
		websiteUrl: "https://distribution.github.io/distribution",
	},
	{
		category: "other",
		containerPort: 11_434,
		description:
			"Runs open-weight LLMs locally. CPU-only as deployed here : GPU access needs device passthrough this app doesn't configure.",
		envVars: {},
		icon: "ollama.svg",
		id: "builtin-ollama",
		image: "ollama/ollama",
		sourceUrl: "https://github.com/ollama/ollama",
		name: "Ollama",
		tag: "latest",
		tags: ["llm", "ai", "models", "inference"],
		websiteUrl: "https://ollama.com",
	},
	{
		category: "other",
		containerPort: 8080,
		description:
			"Chat UI for local models. Point OLLAMA_BASE_URL at an Ollama service on the same network.",
		envVars: {
			OLLAMA_BASE_URL: "http://ollama:11434",
			WEBUI_SECRET_KEY: "change-me-to-a-random-string",
		},
		icon: "open-webui.svg",
		id: "builtin-open-webui",
		image: "ghcr.io/open-webui/open-webui",
		sourceUrl: "https://github.com/open-webui/open-webui",
		name: "Open WebUI",
		tag: "main",
		tags: ["llm", "ai", "chat", "ollama"],
		websiteUrl: "https://openwebui.com",
	},
	{
		category: "other",
		containerPort: 8200,
		description:
			"Scheduled, encrypted backups to S3, WebDAV or a local volume. Set the settings encryption key before deploying.",
		envVars: {
			PGID: "1000",
			PUID: "1000",
			SETTINGS_ENCRYPTION_KEY: "change-me-to-a-random-string",
			TZ: "UTC",
		},
		icon: "duplicati.svg",
		id: "builtin-duplicati",
		image: "lscr.io/linuxserver/duplicati",
		sourceUrl: "https://github.com/duplicati/duplicati",
		name: "Duplicati",
		tag: "latest",
		tags: ["backup", "s3", "encryption", "storage"],
		websiteUrl: "https://duplicati.com",
	},
];
