import type { BuiltinTemplate } from "$lib/server/db/builtin-templates";

export const BUILTIN_TEMPLATES_APPS: BuiltinTemplate[] = [
	{
		category: "analytics",
		containerPort: 3000,
		description:
			"Privacy-focused web analytics. Needs a linked Postgres database.",
		envVars: {
			APP_SECRET: "change-me-to-a-random-32-char-string",
			DATABASE_URL:
				"postgresql://{{db.POSTGRES_USER}}:{{db.POSTGRES_PASSWORD}}@{{db}}:5432/{{db.POSTGRES_DB}}",
		},
		icon: "umami.svg",
		id: "builtin-umami",
		image: "ghcr.io/umami-software/umami",
		sourceUrl: "https://github.com/umami-software/umami",
		name: "Umami",
		tag: "postgresql-latest",
		websiteUrl: "https://umami.is",
	},
	{
		category: "analytics",
		containerPort: 3000,
		description:
			"BI/dashboards over your own data sources. Runs standalone with an embedded database.",
		envVars: {},
		icon: "metabase.svg",
		id: "builtin-metabase",
		image: "metabase/metabase",
		sourceUrl: "https://github.com/metabase/metabase",
		name: "Metabase",
		tag: "latest",
		websiteUrl: "https://www.metabase.com",
	},
	{
		category: "monitoring",
		containerPort: 3000,
		description: "Dashboards and visualization for metrics.",
		envVars: {},
		icon: "grafana.svg",
		id: "builtin-grafana",
		image: "grafana/grafana",
		sourceUrl: "https://github.com/grafana/grafana",
		name: "Grafana",
		tag: "latest",
		websiteUrl: "https://grafana.com",
	},
	{
		category: "monitoring",
		containerPort: 8000,
		description: "Cron job and scheduled task monitoring.",
		envVars: {},
		icon: "healthchecks.svg",
		id: "builtin-healthchecks",
		image: "healthchecks/healthchecks",
		sourceUrl: "https://github.com/healthchecks/healthchecks",
		name: "Healthchecks",
		tag: "latest",
		websiteUrl: "https://healthchecks.io",
	},
	{
		category: "monitoring",
		containerPort: 8080,
		description: "Lightweight uptime/status monitoring dashboard.",
		envVars: {},
		icon: "gatus.svg",
		id: "builtin-gatus",
		image: "ghcr.io/twin/gatus",
		sourceUrl: "https://github.com/TwiN/gatus",
		name: "Gatus",
		tag: "latest",
		websiteUrl: null,
	},
	{
		category: "monitoring",
		containerPort: 5000,
		description: "Watches web pages for changes and notifies you.",
		envVars: {},
		icon: "changedetection.svg",
		id: "builtin-changedetection",
		image: "dgtlmoon/changedetection.io",
		sourceUrl: "https://github.com/dgtlmoon/changedetection.io",
		name: "changedetection.io",
		tag: "latest",
		websiteUrl: "https://changedetection.io",
	},
	{
		category: "other",
		containerPort: 9090,
		description: "Minimal, fast bookmark manager.",
		envVars: {},
		icon: "linkding.svg",
		id: "builtin-linkding",
		image: "sissbruecker/linkding",
		sourceUrl: "https://github.com/sissbruecker/linkding",
		name: "Linkding",
		tag: "latest",
		websiteUrl: null,
	},
	{
		category: "other",
		containerPort: 8080,
		description:
			"Minimalist RSS reader. Needs a linked Postgres database, seeds an initial admin account on first boot (change the placeholder password after logging in).",
		envVars: {
			ADMIN_PASSWORD: "changeme123",
			ADMIN_USERNAME: "admin",
			CREATE_ADMIN: "1",
			DATABASE_URL:
				"postgres://{{db.POSTGRES_USER}}:{{db.POSTGRES_PASSWORD}}@{{db}}:5432/{{db.POSTGRES_DB}}?sslmode=disable",
			RUN_MIGRATIONS: "1",
		},
		icon: "miniflux.svg",
		id: "builtin-miniflux",
		image: "miniflux/miniflux",
		sourceUrl: "https://github.com/miniflux/v2",
		name: "Miniflux",
		tag: "latest",
		websiteUrl: "https://miniflux.app",
	},
	{
		category: "other",
		containerPort: 80,
		description: "RSS feed aggregator with an embedded SQLite database.",
		envVars: {},
		icon: "freshrss.svg",
		id: "builtin-freshrss",
		image: "freshrss/freshrss",
		sourceUrl: "https://github.com/FreshRSS/FreshRSS",
		name: "FreshRSS",
		tag: "latest",
		websiteUrl: "https://freshrss.org",
	},
	{
		category: "other",
		containerPort: 80,
		description:
			"World's most-used blogging and CMS engine. Needs a linked MySQL database.",
		envVars: {
			WORDPRESS_DB_HOST: "{{db}}",
			WORDPRESS_DB_NAME: "{{db.MYSQL_DATABASE}}",
			WORDPRESS_DB_PASSWORD: "{{db.MYSQL_ROOT_PASSWORD}}",
			WORDPRESS_DB_USER: "root",
		},
		icon: "wordpress.svg",
		id: "builtin-wordpress",
		image: "wordpress",
		sourceUrl: "https://github.com/WordPress/WordPress",
		name: "WordPress",
		tag: "latest",
		websiteUrl: "https://wordpress.org",
	},
	{
		category: "other",
		containerPort: 2368,
		description:
			"Blogging platform, runs standalone with an embedded SQLite database.",
		envVars: {},
		icon: "ghost.png",
		id: "builtin-ghost",
		image: "ghost",
		sourceUrl: "https://github.com/TryGhost/Ghost",
		name: "Ghost",
		tag: "latest",
		websiteUrl: "https://ghost.org",
	},
	{
		category: "other",
		containerPort: 8384,
		description: "Continuous, peer-to-peer file synchronization.",
		envVars: {},
		icon: "syncthing.svg",
		id: "builtin-syncthing",
		image: "syncthing/syncthing",
		sourceUrl: "https://github.com/syncthing/syncthing",
		name: "Syncthing",
		tag: "latest",
		websiteUrl: "https://syncthing.net",
	},
	{
		category: "other",
		containerPort: 80,
		description: "Web-based file browser for a mounted directory.",
		envVars: {},
		icon: "filebrowser.svg",
		id: "builtin-filebrowser",
		image: "filebrowser/filebrowser",
		sourceUrl: "https://github.com/filebrowser/filebrowser",
		name: "File Browser",
		tag: "latest",
		websiteUrl: "https://filebrowser.org",
	},
	{
		category: "development",
		containerPort: 3000,
		description:
			"Self-hosted Git service, GitHub-alike. Shows a setup wizard on first visit (choose SQLite there for a zero-config start).",
		envVars: {},
		icon: "gitea.svg",
		id: "builtin-gitea",
		image: "gitea/gitea",
		sourceUrl: "https://github.com/go-gitea/gitea",
		name: "Gitea",
		tag: "latest",
		websiteUrl: "https://about.gitea.com",
	},
	{
		category: "development",
		containerPort: 80,
		description: "Collection of handy developer utilities in one static site.",
		envVars: {},
		icon: "it-tools.svg",
		id: "builtin-it-tools",
		image: "ghcr.io/corentinth/it-tools",
		sourceUrl: "https://github.com/CorentinTh/it-tools",
		name: "IT Tools",
		tag: "latest",
		websiteUrl: "https://it-tools.tech",
	},
	{
		category: "other",
		containerPort: 8080,
		description: "Self-hosted PDF manipulation toolkit.",
		envVars: {},
		icon: "stirling-pdf.svg",
		id: "builtin-stirling-pdf",
		image: "stirlingtools/stirling-pdf",
		sourceUrl: "https://github.com/Stirling-Tools/Stirling-PDF",
		name: "Stirling PDF",
		tag: "latest",
		websiteUrl: "https://stirlingpdf.com",
	},
	{
		category: "other",
		containerPort: 9000,
		description: "Self-hosted web IRC client.",
		envVars: {},
		icon: "thelounge.svg",
		id: "builtin-thelounge",
		image: "thelounge/thelounge",
		sourceUrl: "https://github.com/thelounge/thelounge",
		name: "The Lounge",
		tag: "latest",
		websiteUrl: "https://thelounge.chat",
	},
];
