export interface BuiltinTemplate {
	category: string;
	containerPort: number;
	description: string;
	envVars: Record<string, string>;
	icon: string;
	id: string;
	image: string;
	name: string;
	sourceUrl: string | null;
	tag: string;
	websiteUrl: string | null;
}

export interface BuiltinTemplateLink {
	alias: string;
	id: string;
	linkedTemplateId: string;
	templateId: string;
}

export const BUILTIN_TEMPLATES: BuiltinTemplate[] = [
	{
		category: "cache",
		containerPort: 6379,
		description: "In-memory key-value store. Unauthenticated by default.",
		envVars: {},
		icon: "redis.svg",
		id: "builtin-redis",
		image: "redis",
		sourceUrl: "https://github.com/redis/redis",
		name: "Redis",
		tag: "alpine",
		websiteUrl: "https://redis.io",
	},
	{
		category: "database",
		containerPort: 5432,
		description:
			"Relational database. Review the placeholder password before deploying.",
		envVars: {
			POSTGRES_DB: "app",
			POSTGRES_PASSWORD: "changeme",
			POSTGRES_USER: "postgres",
		},
		icon: "postgres.svg",
		id: "builtin-postgres",
		image: "postgres",
		sourceUrl: "https://github.com/postgres/postgres",
		name: "PostgreSQL",
		tag: "18-alpine",
		websiteUrl: "https://www.postgresql.org",
	},
	{
		category: "database",
		containerPort: 3306,
		description:
			"Relational database. Review the placeholder password before deploying.",
		envVars: {
			MYSQL_DATABASE: "app",
			MYSQL_ROOT_PASSWORD: "changeme",
		},
		icon: "mysql.svg",
		id: "builtin-mysql",
		image: "mysql",
		sourceUrl: "https://github.com/mysql/mysql-server",
		name: "MySQL",
		tag: "8",
		websiteUrl: "https://www.mysql.com",
	},
	{
		category: "database",
		containerPort: 27_017,
		description:
			"Document database. Review the placeholder password before deploying.",
		envVars: {
			MONGO_INITDB_ROOT_PASSWORD: "changeme",
			MONGO_INITDB_ROOT_USERNAME: "admin",
		},
		icon: "mongodb.svg",
		id: "builtin-mongodb",
		image: "mongo",
		sourceUrl: "https://github.com/mongodb/mongo",
		name: "MongoDB",
		tag: "7",
		websiteUrl: "https://www.mongodb.com",
	},
	{
		category: "other",
		containerPort: 8080,
		description:
			"Lightweight database admin UI (works with Postgres/MySQL/etc).",
		envVars: {},
		icon: "adminer.svg",
		id: "builtin-adminer",
		image: "adminer",
		sourceUrl: "https://github.com/vrana/adminer",
		name: "Adminer",
		tag: "latest",
		websiteUrl: "https://www.adminer.org",
	},
	{
		category: "monitoring",
		containerPort: 3001,
		description: "Self-hosted uptime monitoring with status pages.",
		envVars: {},
		icon: "uptime-kuma.svg",
		id: "builtin-uptime-kuma",
		image: "louislam/uptime-kuma",
		sourceUrl: "https://github.com/louislam/uptime-kuma",
		name: "Uptime Kuma",
		tag: "2",
		websiteUrl: "https://uptime.kuma.pet",
	},
	{
		category: "automation",
		containerPort: 5678,
		description: "Workflow automation tool.",
		envVars: {},
		icon: "n8n.svg",
		id: "builtin-n8n",
		image: "n8nio/n8n",
		sourceUrl: "https://github.com/n8n-io/n8n",
		name: "n8n",
		tag: "latest",
		websiteUrl: "https://n8n.io",
	},
	{
		category: "other",
		containerPort: 80,
		description: "Self-hosted password manager (Bitwarden-compatible server).",
		envVars: {},
		icon: "vaultwarden.svg",
		id: "builtin-vaultwarden",
		image: "vaultwarden/server",
		sourceUrl: "https://github.com/dani-garcia/vaultwarden",
		name: "Vaultwarden",
		tag: "latest",
		websiteUrl: null,
	},
	{
		category: "media",
		containerPort: 8096,
		description: "Media server for movies, TV, and music.",
		envVars: {},
		icon: "jellyfin.svg",
		id: "builtin-jellyfin",
		image: "jellyfin/jellyfin",
		sourceUrl: "https://github.com/jellyfin/jellyfin",
		name: "Jellyfin",
		tag: "latest",
		websiteUrl: "https://jellyfin.org",
	},
	{
		category: "media",
		containerPort: 4533,
		description: "Music streaming server with a Subsonic-compatible API.",
		envVars: {},
		icon: "navidrome.svg",
		id: "builtin-navidrome",
		image: "deluan/navidrome",
		sourceUrl: "https://github.com/navidrome/navidrome",
		name: "Navidrome",
		tag: "latest",
		websiteUrl: "https://www.navidrome.org",
	},
	{
		category: "media",
		containerPort: 80,
		description: "Self-hosted audiobook and podcast server.",
		envVars: {},
		icon: "audiobookshelf.svg",
		id: "builtin-audiobookshelf",
		image: "advplyr/audiobookshelf",
		sourceUrl: "https://github.com/advplyr/audiobookshelf",
		name: "Audiobookshelf",
		tag: "latest",
		websiteUrl: "https://www.audiobookshelf.org",
	},
	{
		category: "media",
		containerPort: 8989,
		description: "TV show collection manager and downloader.",
		envVars: {},
		icon: "sonarr.svg",
		id: "builtin-sonarr",
		image: "linuxserver/sonarr",
		sourceUrl: "https://github.com/Sonarr/Sonarr",
		name: "Sonarr",
		tag: "latest",
		websiteUrl: "https://sonarr.tv",
	},
	{
		category: "media",
		containerPort: 7878,
		description: "Movie collection manager and downloader.",
		envVars: {},
		icon: "radarr.svg",
		id: "builtin-radarr",
		image: "linuxserver/radarr",
		sourceUrl: "https://github.com/Radarr/Radarr",
		name: "Radarr",
		tag: "latest",
		websiteUrl: "https://radarr.video",
	},
	{
		category: "media",
		containerPort: 9696,
		description: "Indexer manager, feeds Sonarr/Radarr/Lidarr.",
		envVars: {},
		icon: "prowlarr.svg",
		id: "builtin-prowlarr",
		image: "linuxserver/prowlarr",
		sourceUrl: "https://github.com/Prowlarr/Prowlarr",
		name: "Prowlarr",
		tag: "latest",
		websiteUrl: null,
	},
	{
		category: "media",
		containerPort: 6767,
		description: "Subtitle manager for Sonarr/Radarr libraries.",
		envVars: {},
		icon: "bazarr.svg",
		id: "builtin-bazarr",
		image: "linuxserver/bazarr",
		sourceUrl: "https://github.com/morpheus65535/bazarr",
		name: "Bazarr",
		tag: "latest",
		websiteUrl: "https://www.bazarr.media",
	},
	{
		category: "media",
		containerPort: 8686,
		description: "Music collection manager and downloader.",
		envVars: {},
		icon: "lidarr.svg",
		id: "builtin-lidarr",
		image: "linuxserver/lidarr",
		sourceUrl: "https://github.com/Lidarr/Lidarr",
		name: "Lidarr",
		tag: "latest",
		websiteUrl: "https://lidarr.audio",
	},
	{
		category: "media",
		containerPort: 5055,
		description: "Media request manager for a Jellyfin/Plex library.",
		envVars: {},
		icon: "jellyseerr.svg",
		id: "builtin-jellyseerr",
		image: "fallenbagel/jellyseerr",
		sourceUrl: "https://github.com/Fallenbagel/jellyseerr",
		name: "Jellyseerr",
		tag: "latest",
		websiteUrl: null,
	},
	{
		category: "media",
		containerPort: 5055,
		description: "Media request manager for a Plex library.",
		envVars: {},
		icon: "overseerr.svg",
		id: "builtin-overseerr",
		image: "lscr.io/linuxserver/overseerr",
		sourceUrl: "https://github.com/sct/overseerr",
		name: "Overseerr",
		tag: "latest",
		websiteUrl: "https://overseerr.dev",
	},
	{
		category: "media",
		containerPort: 8080,
		description: "BitTorrent client with a web UI.",
		envVars: {},
		icon: "qbittorrent.svg",
		id: "builtin-qbittorrent",
		image: "linuxserver/qbittorrent",
		sourceUrl: "https://github.com/qbittorrent/qBittorrent",
		name: "qBittorrent",
		tag: "latest",
		websiteUrl: "https://www.qbittorrent.org",
	},
	{
		category: "media",
		containerPort: 9091,
		description: "Lightweight BitTorrent client with a web UI.",
		envVars: {},
		icon: "transmission.svg",
		id: "builtin-transmission",
		image: "linuxserver/transmission",
		sourceUrl: "https://github.com/transmission/transmission",
		name: "Transmission",
		tag: "latest",
		websiteUrl: "https://transmissionbt.com",
	},
	{
		category: "media",
		containerPort: 2342,
		description:
			"AI-powered photo management. Ships with an embedded SQLite database for small libraries.",
		envVars: {},
		icon: "photoprism.svg",
		id: "builtin-photoprism",
		image: "photoprism/photoprism",
		sourceUrl: "https://github.com/photoprism/photoprism",
		name: "PhotoPrism",
		tag: "latest",
		websiteUrl: "https://www.photoprism.app",
	},
	{
		category: "media",
		containerPort: 8083,
		description: "Web UI for browsing and reading a Calibre e-book library.",
		envVars: {},
		icon: "calibre-web.svg",
		id: "builtin-calibre-web",
		image: "lscr.io/linuxserver/calibre-web",
		sourceUrl: "https://github.com/janeczku/calibre-web",
		name: "Calibre-Web",
		tag: "latest",
		websiteUrl: null,
	},
	{
		category: "network",
		containerPort: 80,
		description:
			"Network-wide ad blocker. Only its web admin UI is reachable here : DNS itself needs host network mode, set on the Networking tab after deploying.",
		envVars: {},
		icon: "pihole.svg",
		id: "builtin-pihole",
		image: "pihole/pihole",
		sourceUrl: "https://github.com/pi-hole/pi-hole",
		name: "Pi-hole",
		tag: "latest",
		websiteUrl: "https://pi-hole.net",
	},
	{
		category: "network",
		containerPort: 3000,
		description:
			"Ad-blocking DNS server with a setup wizard on first visit. Only its web UI is reachable here : DNS itself needs host network mode, set on the Networking tab after deploying.",
		envVars: {},
		icon: "adguard-home.svg",
		id: "builtin-adguard-home",
		image: "adguard/adguardhome",
		sourceUrl: "https://github.com/AdguardTeam/AdGuardHome",
		name: "AdGuard Home",
		tag: "latest",
		websiteUrl: "https://adguard.com/en/adguard-home/overview.html",
	},
	{
		category: "network",
		containerPort: 81,
		description: "Web UI for managing Nginx reverse proxy hosts and certs.",
		envVars: {},
		icon: "nginx-proxy-manager.svg",
		id: "builtin-nginx-proxy-manager",
		image: "jc21/nginx-proxy-manager",
		sourceUrl: "https://github.com/NginxProxyManager/nginx-proxy-manager",
		name: "Nginx Proxy Manager",
		tag: "latest",
		websiteUrl: "https://nginxproxymanager.com",
	},
	{
		category: "network",
		containerPort: 9000,
		description: "Web UI for managing this and other Docker hosts.",
		envVars: {},
		icon: "portainer.svg",
		id: "builtin-portainer",
		image: "portainer/portainer-ce",
		sourceUrl: "https://github.com/portainer/portainer",
		name: "Portainer",
		tag: "latest",
		websiteUrl: "https://www.portainer.io",
	},
	{
		category: "network",
		containerPort: 80,
		description: "Tracks internet speed test results over time.",
		envVars: {},
		icon: "speedtest-tracker.svg",
		id: "builtin-speedtest-tracker",
		image: "lscr.io/linuxserver/speedtest-tracker",
		sourceUrl: "https://github.com/alexjustesen/speedtest-tracker",
		name: "Speedtest Tracker",
		tag: "latest",
		websiteUrl: "https://speedtest-tracker.dev",
	},
	{
		category: "dashboard",
		containerPort: 3000,
		description: "Static, fast, YAML-configured start page for your services.",
		envVars: {},
		icon: "homepage.svg",
		id: "builtin-homepage",
		image: "ghcr.io/gethomepage/homepage",
		sourceUrl: "https://github.com/gethomepage/homepage",
		name: "Homepage",
		tag: "latest",
		websiteUrl: "https://gethomepage.dev",
	},
	{
		category: "dashboard",
		containerPort: 8080,
		description: "Configurable start page for self-hosted services.",
		envVars: {},
		icon: "dashy.png",
		id: "builtin-dashy",
		image: "lissy93/dashy",
		sourceUrl: "https://github.com/Lissy93/dashy",
		name: "Dashy",
		tag: "latest",
		websiteUrl: "https://dashy.to",
	},
	{
		category: "dashboard",
		containerPort: 7575,
		description: "Customizable start page with app/service widgets.",
		envVars: {},
		icon: "homarr.svg",
		id: "builtin-homarr",
		image: "ghcr.io/homarr-labs/homarr",
		sourceUrl: "https://github.com/homarr-labs/homarr",
		name: "Homarr",
		tag: "latest",
		websiteUrl: "https://homarr.dev",
	},
	{
		category: "productivity",
		containerPort: 8080,
		description: "Hierarchical note-taking app with encryption support.",
		envVars: {},
		icon: "trilium.png",
		id: "builtin-trilium",
		image: "triliumnext/trilium",
		sourceUrl: "https://github.com/TriliumNext/Trilium",
		name: "Trilium Notes",
		tag: "latest",
		websiteUrl: null,
	},
	{
		category: "productivity",
		containerPort: 3000,
		description: "Collaborative markdown notes, Notion-alternative-ish.",
		envVars: {},
		icon: "hedgedoc.svg",
		id: "builtin-hedgedoc",
		image: "quay.io/hedgedoc/hedgedoc",
		sourceUrl: "https://github.com/hedgedoc/hedgedoc",
		name: "HedgeDoc",
		tag: "latest",
		websiteUrl: "https://hedgedoc.org",
	},
	{
		category: "productivity",
		containerPort: 22_300,
		description: "Sync server for the Joplin note-taking app.",
		envVars: {},
		icon: "joplin-server.svg",
		id: "builtin-joplin-server",
		image: "joplin/server",
		sourceUrl: "https://github.com/laurent22/joplin",
		name: "Joplin Server",
		tag: "latest",
		websiteUrl: "https://joplinapp.org",
	},
	{
		category: "productivity",
		containerPort: 3000,
		description:
			"Wiki platform with a setup wizard on first visit (choose SQLite there for a zero-config start).",
		envVars: {},
		icon: "wikijs.svg",
		id: "builtin-wikijs",
		image: "requarks/wiki",
		sourceUrl: "https://github.com/requarks/wiki",
		name: "Wiki.js",
		tag: "latest",
		websiteUrl: "https://js.wiki",
	},
	{
		category: "productivity",
		containerPort: 80,
		description: "Collaborative whiteboarding tool.",
		envVars: {},
		icon: "excalidraw.svg",
		id: "builtin-excalidraw",
		image: "excalidraw/excalidraw",
		sourceUrl: "https://github.com/excalidraw/excalidraw",
		name: "Excalidraw",
		tag: "latest",
		websiteUrl: "https://excalidraw.com",
	},
	{
		category: "productivity",
		containerPort: 9001,
		description: "Real-time collaborative document/notepad editor.",
		envVars: {},
		icon: "etherpad.svg",
		id: "builtin-etherpad",
		image: "etherpad/etherpad",
		sourceUrl: "https://github.com/ether/etherpad-lite",
		name: "Etherpad",
		tag: "latest",
		websiteUrl: "https://etherpad.org",
	},
	{
		category: "productivity",
		containerPort: 3456,
		description: "Self-hosted to-do list and project management app.",
		envVars: {},
		icon: "vikunja.svg",
		id: "builtin-vikunja",
		image: "vikunja/vikunja",
		sourceUrl: "https://github.com/go-vikunja/vikunja",
		name: "Vikunja",
		tag: "latest",
		websiteUrl: "https://vikunja.io",
	},
	{
		category: "finance",
		containerPort: 5006,
		description: "Local-first personal budgeting app (YNAB-alike).",
		envVars: {},
		icon: "actual-budget.svg",
		id: "builtin-actual-budget",
		image: "actualbudget/actual-server",
		sourceUrl: "https://github.com/actualbudget/actual",
		name: "Actual Budget",
		tag: "latest",
		websiteUrl: "https://actualbudget.org",
	},
];

export const BUILTIN_TEMPLATE_LINKS: BuiltinTemplateLink[] = [
	{
		alias: "db",
		id: "builtin-link-wordpress-mysql",
		linkedTemplateId: "builtin-mysql",
		templateId: "builtin-wordpress",
	},
	{
		alias: "db",
		id: "builtin-link-umami-postgres",
		linkedTemplateId: "builtin-postgres",
		templateId: "builtin-umami",
	},
	{
		alias: "db",
		id: "builtin-link-miniflux-postgres",
		linkedTemplateId: "builtin-postgres",
		templateId: "builtin-miniflux",
	},
];
