name: CI
on:
  workflow_call:

permissions:
  contents: read

env:
  TZ: Europe/Paris
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
  CI: "true"
  COLUMNS: "9999"
  NO_COLOR: "1"

jobs:
  markdown:
    name: Linting / Formatting (MD)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Check markdown linting
        run: bun run lint:md

      - name: Check markdown formatting
        run: bun run format:md:check

  ts-check:
    name: Linting / Formatting (TS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Generate SvelteKit types
        run: |
          echo "Generating SvelteKit types..."
          if bun run svelte-kit sync; then
              echo "SvelteKit types generated successfully."
          else
              echo "Failed to generate SvelteKit types."
              exit 1
          fi

      - name: Type check Webapp
        run:
          bun run svelte-check --tsconfig ./tsconfig.json --fail-on-warnings
          --tsgo

      - name: Type check Packages
        run: |
          bun run check:agent
          bun run check:cli
          bun run check:installer

      - name: Lint
        run: bun run lint

  ts-test:
    name: Tests (TS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Install socat
        run: sudo apt-get update && sudo apt-get install -y socat

      - name: Tests (Unit)
        run:
          bun run test:unit -- --coverage-reporter=lcov
          --coverage-dir=coverage/unit

      - name: Tests (Integration)
        run:
          bun run test:integration -- --coverage-reporter=lcov
          --coverage-dir=coverage/integration

      - name: Upload coverage report
        if: always()
        uses: orochibraru/upload-artifact@v8
        with:
          name: coverage-report
          path: coverage/
          if-no-files-found: warn
          retention-days: 14
