name: PR Cleanup

on:
  pull_request:
    types: [closed]

concurrency:
  group: pr-cleanup-${{ github.event.pull_request.number }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  delete-images:
    name: Delete PR Images
    if:
      ${{ !github.event.pull_request.merged &&
      github.event.pull_request.head.repo.full_name == github.repository }}
    uses: ./.github/workflows/delete-pr-images.yaml
    with:
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
