name: Publish
on:
  push:
    branches:
      - main

concurrency:
  group: publish
  cancel-in-progress: false

env:
  TZ: Europe/Paris

permissions:
  contents: read
  packages: write

jobs:
  code_quality:
    name: Code Quality
    uses: ./.github/workflows/code_quality.yaml

  build:
    name: Docker Build
    uses: ./.github/workflows/docker.yaml
    needs:
      - code_quality
    with:
      image_tag: ${{ github.sha }}
    secrets:
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
