name: Pull Request
on:
  pull_request:

concurrency:
  group: pull-request-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  TZ: Europe/Paris

permissions:
  contents: read
  packages: write

jobs:
  code_quality:
    name: Code Quality
    uses: ./.github/actions/code_quality.yaml

  build:
    name: Docker Build
    uses: ./.github/actions/docker.yaml
    needs:
      - code_quality
    with:
      image_tag: pr-${{ github.event.pull_request.number }}
    secrets:
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
