name: Pull Request
on:
  pull_request:

concurrency:
  group: pull-request-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  TZ: Europe/Paris

permissions:
  contents: read
  packages: write

jobs:
  code_quality:
    name: Code Quality
    uses: ./.github/workflows/code_quality.yaml

  build:
    name: Docker Build
    uses: ./.github/workflows/docker.yaml
    needs:
      - code_quality
    with:
      image_tag: pr-${{ github.event.pull_request.number }}
      image_name: orochibraru/homerun
      registry_name: git.ombrage.space
      registry_username: orochibraru
    secrets:
      registry_password: ${{ secrets.GITEA_TOKEN }}
