import {
	Activity,
	BookOpen,
	Boxes,
	CalendarClock,
	Clock,
	CloudUpload,
	Container,
	Database,
	FolderKanban,
	GitBranch,
	HardDrive,
	KeyRound,
	LayoutDashboard,
	LayoutGrid,
	Network,
	ScrollText,
	Send,
	Server,
	Settings,
	Trash2,
	Users,
} from "@lucide/svelte";
import { resolve } from "$app/paths";

export const allNavItems = [
	{
		adminOnly: false,
		category: "Workspace",
		exact: true,
		href: resolve("/"),
		icon: LayoutDashboard,
		label: "Overview",
	},
	{
		adminOnly: false,
		category: "Workspace",
		exact: false,
		href: resolve("/services"),
		icon: Server,
		label: "Services",
	},
	{
		adminOnly: false,
		category: "Workspace",
		exact: false,
		href: resolve("/stacks"),
		icon: FolderKanban,
		label: "Stacks",
	},
	{
		adminOnly: false,
		category: "Workspace",
		exact: false,
		href: resolve("/templates"),
		icon: LayoutGrid,
		label: "Templates",
	},
	{
		adminOnly: false,
		category: "Workspace",
		exact: false,
		href: resolve("/cron-jobs"),
		icon: Clock,
		label: "Cron Jobs",
	},
	{
		adminOnly: false,
		category: "Workspace",
		exact: false,
		href: resolve("/status-pages"),
		icon: Activity,
		label: "Status Page",
	},
	{
		adminOnly: false,
		category: "Infrastructure",
		exact: false,
		href: resolve("/storage"),
		icon: HardDrive,
		label: "Storage",
	},
	{
		adminOnly: false,
		category: "Infrastructure",
		exact: false,
		href: resolve("/backups"),
		icon: CloudUpload,
		label: "Backups",
	},
	{
		adminOnly: false,
		category: "Infrastructure",
		exact: false,
		href: resolve("/s3-destinations"),
		icon: Database,
		label: "S3 Destinations",
	},
	{
		adminOnly: false,
		category: "Infrastructure",
		exact: false,
		href: resolve("/remote-hosts"),
		icon: Network,
		label: "Remote Hosts",
	},
	{
		adminOnly: false,
		category: "Infrastructure",
		exact: false,
		href: resolve("/scheduling"),
		icon: CalendarClock,
		label: "Scheduling",
	},
	{
		adminOnly: false,
		category: "Integrations",
		exact: false,
		href: resolve("/git-providers"),
		icon: GitBranch,
		label: "Git Providers",
	},
	{
		adminOnly: false,
		category: "Integrations",
		exact: false,
		href: resolve("/build-cache-registries"),
		icon: Container,
		label: "Build Cache",
	},
	{
		adminOnly: false,
		category: "Integrations",
		exact: false,
		href: resolve("/notification-channels"),
		icon: Send,
		label: "Notification Channels",
	},
	{
		adminOnly: false,
		category: "Integrations",
		exact: false,
		href: resolve("/api-docs"),
		icon: BookOpen,
		label: "API Docs",
	},
	{
		adminOnly: true,
		category: "Administration",
		exact: false,
		href: resolve("/users"),
		icon: Users,
		label: "Users",
	},
	{
		adminOnly: true,
		category: "Administration",
		exact: false,
		href: resolve("/authentication"),
		icon: KeyRound,
		label: "Authentication",
	},
	{
		adminOnly: true,
		category: "Administration",
		exact: false,
		href: resolve("/settings"),
		icon: Settings,
		label: "Settings",
	},
	{
		adminOnly: true,
		category: "Administration",
		exact: false,
		href: resolve("/system-logs"),
		icon: ScrollText,
		label: "System Logs",
	},
	{
		adminOnly: true,
		category: "Administration",
		exact: false,
		href: resolve("/registry"),
		icon: Boxes,
		label: "Registry",
	},
	{
		adminOnly: true,
		category: "Administration",
		exact: false,
		href: resolve("/docker-cleanup"),
		icon: Trash2,
		label: "Docker Cleanup",
	},
];
