import {
	Activity,
	ArrowRightLeft,
	BarChart3,
	BookOpen,
	Boxes,
	CalendarClock,
	Clock,
	CloudUpload,
	Container,
	Cylinder,
	Database,
	FileCode2,
	Fingerprint,
	FolderKanban,
	GitBranch,
	Globe,
	HardDrive,
	History,
	KeyRound,
	LayoutDashboard,
	LayoutGrid,
	Network,
	ScrollText,
	Send,
	Server,
	Settings,
	TerminalSquare,
	Trash2,
	Users,
} from "@lucide/svelte";
import { resolve } from "$app/paths";

export const allNavItems = [
	{
		category: "Workspace",
		exact: true,
		href: resolve(""),
		icon: LayoutDashboard,
		label: "Overview",
	},
	{
		category: "Workspace",
		exact: false,
		href: resolve("services"),
		icon: Server,
		label: "Services",
	},
	{
		category: "Workspace",
		exact: false,
		href: resolve("deployments"),
		icon: History,
		label: "Deployments",
	},
	{
		category: "Workspace",
		exact: false,
		href: resolve("monitoring"),
		icon: BarChart3,
		label: "Monitoring",
	},
	{
		category: "Workspace",
		exact: false,
		href: resolve("stacks"),
		icon: FolderKanban,
		label: "Stacks",
	},
	{
		category: "Workspace",
		exact: false,
		href: resolve("templates"),
		icon: LayoutGrid,
		label: "Templates",
	},
	{
		category: "Workspace",
		exact: false,
		href: resolve("cron-jobs"),
		icon: Clock,
		label: "Cron Jobs",
	},
	{
		category: "Workspace",
		exact: false,
		href: resolve("status-pages"),
		icon: Activity,
		label: "Status Page",
	},
	{
		category: "Storage",
		exact: false,
		href: resolve("storage"),
		icon: HardDrive,
		label: "Volumes",
	},
	{
		category: "Storage",
		exact: false,
		href: resolve("backups"),
		icon: CloudUpload,
		label: "Backups",
	},
	{
		category: "Storage",
		exact: false,
		href: resolve("s3-destinations"),
		icon: Database,
		label: "Backup Destinations",
	},
	{
		category: "Storage",
		exact: false,
		href: resolve("object-storage"),
		icon: Cylinder,
		label: "Object Storage",
	},
	{
		category: "Infrastructure",
		exact: false,
		href: resolve("remote-hosts"),
		icon: Network,
		label: "Remote Hosts",
	},
	{
		category: "Infrastructure",
		exact: false,
		href: resolve("redirects"),
		icon: ArrowRightLeft,
		label: "Redirects",
	},
	{
		category: "Infrastructure",
		exact: false,
		href: resolve("scheduling"),
		icon: CalendarClock,
		label: "Scheduling",
	},
	{
		category: "Infrastructure",
		exact: false,
		href: resolve("terminal"),
		icon: TerminalSquare,
		label: "Terminal",
	},
	{
		category: "Integrations",
		exact: false,
		href: resolve("git-providers"),
		icon: GitBranch,
		label: "Git Providers",
	},
	{
		category: "Integrations",
		exact: false,
		href: resolve("build-cache-registries"),
		icon: Container,
		label: "Build Cache",
	},
	{
		category: "Integrations",
		exact: false,
		href: resolve("notification-channels"),
		icon: Send,
		label: "Notification Channels",
	},
	{
		category: "Integrations",
		exact: false,
		href: resolve("dns"),
		icon: Globe,
		label: "DNS",
	},
	{
		category: "Integrations",
		exact: false,
		href: resolve("idp"),
		icon: Fingerprint,
		label: "IDP",
	},
	{
		category: "Integrations",
		exact: false,
		href: resolve("iac"),
		icon: FileCode2,
		label: "Infrastructure as Code",
	},
	{
		category: "Integrations",
		exact: false,
		href: resolve("api-docs"),
		icon: BookOpen,
		label: "API Docs",
	},
	{
		category: "Administration",
		exact: false,
		href: resolve("users"),
		icon: Users,
		label: "Users",
	},
	{
		category: "Administration",
		exact: false,
		href: resolve("authentication"),
		icon: KeyRound,
		label: "Authentication",
	},
	{
		category: "Administration",
		exact: false,
		href: resolve("settings"),
		icon: Settings,
		label: "Settings",
	},
	{
		category: "Administration",
		exact: false,
		href: resolve("system-logs"),
		icon: ScrollText,
		label: "System Logs",
	},
	{
		category: "Administration",
		exact: false,
		href: resolve("registry"),
		icon: Boxes,
		label: "Registry",
	},
	{
		category: "Administration",
		exact: false,
		href: resolve("docker-cleanup"),
		icon: Trash2,
		label: "Docker Cleanup",
	},
];
